name: Docker Compose
on:
  repository_dispatch:
    types: [redeploy-on-vps]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Clear containers
      run: docker ps -aq | xargs -r docker rm -f
    - name: Clear images
      run: docker images -aq | xargs -r docker rmi -f
    - name: Run Docker Compose
      run: docker compose up -d